// <auto-generated />
using CompaniesAnalysis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompaniesAnalysis.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CompaniesAnalysis.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<int>("Cik")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cik")
                        .IsUnique()
                        .HasDatabaseName("IX_Companies_Cik");

                    b.HasIndex("EntityName")
                        .HasDatabaseName("IX_Companies_EntityName");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("CompaniesAnalysis.Domain.Entities.IncomeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasPrecision(28, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_IncomeRecords_CompanyId_Year");

                    b.ToTable("IncomeRecords", (string)null);
                });

            modelBuilder.Entity("CompaniesAnalysis.Domain.Entities.IncomeRecord", b =>
                {
                    b.HasOne("CompaniesAnalysis.Domain.Entities.Company", "Company")
                        .WithMany("IncomeRecords")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompaniesAnalysis.Domain.Entities.Company", b =>
                {
                    b.Navigation("IncomeRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
